fix: fix error which is occurring on production
error: abstractExtensionService.ts:396 Activating extension 'nju33.vscode-user-status' failed: Cannot find module 'apollo-link-http'